### ISSUE TITLE
[Bug]: Neofetch Stucks

### ISSUE THREAD

**Issue by T-Dynamos** [xeffyr/android-vshell#17]
### Problem description

I don't know

### What steps will reproduce the bug?

Neofetch

### What is the expected behavior?

```
~# neofetch
```
after memory info it is stuck and when we press ctrl +c then it says process code completed and exits

### Android OS version

7

### Device CPU architecture

Aarch64

**Comment by WMCB-Tech** [comment]
In case for neofetch is stuck that is performance of bash, `bash` tends to be slower than `dash` and of course. don't forget you're running under qemu emulator so it is expected

**Comment by xeffyr** [comment]
TL DR: https://github.com/xeffyr/android-vshell/blob/master/LIMITATIONS.md#requires-a-high-end-device

Neofetch works, just takes some time to load. On my device this is 8 seconds. Remember that you are under QEMU, everything is much slower.

![Screenshot_20210820-112509](https://user-images.githubusercontent.com/25881154/130204553-42da4a61-775c-48a2-b28a-242873389967.png)

Don't be confused by "997 MHz" in stats. It actually feels like a very old PC with 100-200 MHz CPU.
