### ISSUE TITLE
[Feature]: Multiple Session with SSH

### ISSUE THREAD

**Issue by Yonle** [xeffyr/android-vshell#21]
### Feature description

Regarding this note in [LIMITATIONS.md](https://github.com/xeffyr/android-vshell/blob/master/LIMITATIONS.md):

> ## Only one terminal session
> 
> *This limit arises from a fact that vShell doesn't use QEMU as external
program. Instead it is merged with terminal emulator code. It is possible
to implement multiple sessions but will require lot of work.*

The new vShell version supports SSH Forwarding as what i expected. So i guess we can make Multiple Session support with SSH?

Yes i know vShell only support 1 Session. I only asking does this feature will implemented with SSH Help.

### Design limits acknowledgement

- [x] I have read and understand [LIMITATIONS.md](https://github.com/xeffyr/android-vshell/blob/master/LIMITATIONS.md)

**Comment by xeffyr** [comment]
You have not read or seem do not understand what is described in LIMITATIONS.md file.

> Application user interface is very minimal
>
> Only important & easy to implement things: console, special keys row, context menu for extra actions, application user guide. My occupation is not related to Android development, sorry.
>
> If you need something that is more customizable, please use Termux instead. It can run Alpine Linux in QEMU as well (recommending to try proot - it's faster).

I have intentionally removed drawer and other non-vital things which would be troublesome to keep up, leaving the bare terminal and few other elements only.

**Comment by xeffyr** [comment]
Also on SSH client: this won't be possible without significant changes to application. As QEMU has been merged with terminal library, it is not possible to start more than one session anymore, otherwise each session will result in separate QEMU instance.
