### ISSUE TITLE
Timeout on vscode server

### ISSUE THREAD

**Issue by ichit** [xeffyr/android-vshell#23]
Hi thanks for the vshell app. I sucessfully installed Vscode server on it and tried to run it, but after sometime, it says timeout. I just wanted to ask if there is anything i can do to get it running. I wish i could use vscode for on the go coding with it. thanks

**Comment by xeffyr** [comment]
This happens because `node` execution is to slow. Even if you manage to get vscode or code-server to get started, possibly there would be further performance issues.
