### ISSUE TITLE
[Bug]: Sharing dirs does not work for aarch64 (but works for x86_64)

### ISSUE THREAD

**Issue by 4ntoine** [xeffyr/android-vshell#25]
### Problem description

Sharing does not work for aarch64 image (`No such device`), but works for x86_64 image.

### What steps will reproduce the bug?

0. check out my [fork](https://bitbucket.org/4ntoine/android-vshell/)
note my [changes](https://bitbucket.org/4ntoine/android-vshell/commits/812e82be2d135f32ddd18fdd50a111b214506c8b).
sorry i was unable to push on github due to large files limitation (even with LFS enabled).
1. set [`isArmVM`](https://bitbucket.org/4ntoine/android-vshell/src/812e82be2d135f32ddd18fdd50a111b214506c8b/app/src/main/java/app/virtshell/TerminalActivity.java#lines-397) to `false` in `TerminalActivity`
2. install and run the app

In the app:
1. Log in to the VM:
login: `root`
password: `vm`
2. Try to mount the host_user:
`mount -t 9p -o trans=virtio host_user /root/app/user -oversion=9p2000.L,msize=131072`
3. create a file in Android Studio IDE or using `adb` in/data/data/app.virtshell/files/shared/user
4. make sure you can see it with `ls /root/app/user/`

on x86_64 you will be able to see the file you've just created.
now change `isArmVM` to `true`, recompile, rerun and repeat the steps.
on aarch64 you will get `No such device` message:
![device-2021-11-15-232816](https://user-images.githubusercontent.com/846671/141840071-20cd478a-837c-4fc3-b43d-7ebde4a39c21.png)

### What is the expected behavior?

the dir is shared

### Application version

1.19

### Android OS version

10

### Device CPU architecture

aarch64, x86_64

**Comment by 4ntoine** [comment]
I'm happy to assist in fixing it, probably try smth quickly (like additional/adjusted qemu args, etc).

**Comment by 4ntoine** [comment]
@xeffyr Is there any debug output i can turn on to check what's happening inside?

**Comment by WMCB-Tech** [comment]
@4ntoine I think that's due to 9pfs isn't enabled by alpine kernel. check for `zcat /proc/config.gz | grep 9P`

**Comment by 4ntoine** [comment]
@WMCB-Tech is it meant to be executed on running vm or live iso? Running vm does not have `/proc/config.gz` (alpine linux 3.14.2 used, aarch64):
```
# ls /proc/
1              1965           425            execdomains    net
10             1972           438            filesystems    pagetypeinfo
11             1973           477            fs             partitions
12             1974           5              interrupts     sched_debug
120            1975           6              iomem          schedstat
13             1976           7              ioports        scsi
1302           1977           8              irq            self
1367           1978           9              kallsyms       softirqs
14             2              957            key-users      stat
15             2004           958            keys           swaps
16             2028           acpi           kmsg           sys
1694           2029           buddyinfo      kpagecgroup    sysrq-trigger
17             210            bus            kpagecount     sysvipc
175            212            cgroups        kpageflags     thread-self
176            213            cmdline        loadavg        timer_list
1764           25             consoles       locks          tty
177            3              cpuinfo        mdstat         uptime
179            312            crypto         meminfo        version
1846           4              devices        misc           vmallocinfo
1902           409            diskstats      modules        vmstat
1929           422            driver         mounts         zoneinfo
```

**Comment by WMCB-Tech** [comment]
I don't think alpine live media does not have that file, but when you install it you'll be able to see that. 

although here is my screenshot of alpine arm64, which 9p wasn't enabled by kernel compile time
![image](https://user-images.githubusercontent.com/65075766/143183163-241d765a-53e7-496a-9bbe-5c5b56697e8e.png)

**Comment by 4ntoine** [comment]
that's strange, i can't find it anywhere:
```
:~# find / -name config.gz
:~#
```
alpine was installed in `sys` mode

**Comment by 4ntoine** [comment]
got the following:
```
cat /boot/config-virt | grep 9P
CONFIG_NET_9P=m
CONFIG_NET_9P_VIRTIO=m
CONFIG_NET_9P_XEN=m
# CONFIG_NET_9P_DEBUG is not set
CONFIG_9P_FS=m
CONFIG_9P_FSCACHE=y
CONFIG_9P_FS_POSIX_ACL=y
# CONFIG_9P_FS_SECURITY is not set
```

**Comment by 4ntoine** [comment]
@WMCB-Tech thanks for the clue, closing it.
