### ISSUE TITLE
[Bug]: v1.20 does not boot

### ISSUE THREAD

**Issue by jfitie** [xeffyr/android-vshell#26]
### Problem description

When starting, the following message appears:
/sbin/init not found in new root. Launching emergency recovery shell

### What steps will reproduce the bug?

Install v1.20. Force stop and clear data. Start app.

### What is the expected behavior?

Boot to a usable operating system and ask for root password.

### Application version

v1.20

### Android OS version

9, 11 (multiple devices)

### Device CPU architecture

AArch64

**Comment by xeffyr** [comment]
Confirming that issue exists, perhaps the supplied apkovl no longer works after upgrading Alpine Linux to 3.15.0.

I will look like into getting rid of apkovl in favor of using [custom Alpine Linux image](https://wiki.alpinelinux.org/wiki/How_to_make_a_custom_ISO_image_with_mkimage) as this will help to avoid issues like this one in future.
