### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gowwe** [xeffyr/android-vshell#27]
### Problem description

When I download a package and exit the app, and enter again it deletes everything

### What steps will reproduce the bug?

When I download a package and exit the app, and enter again it deletes everything

### What is the expected behavior?

When I download a package and exit the app, and enter again it deletes everything

### Application version

1.14

### Android OS version

10

### Device CPU architecture

arm64

**Comment by WMCB-Tech** [comment]
The data is stored in ram and will be flushed once rebooted. `lbu commit` saves them so in reboot your package will be saved
BTW: the installation is running off Alpine CD Image so everything does not persist beyond session end

**Comment by xeffyr** [comment]
Expected behavior. **Please read everything that is printed while using the app!** As said in motd, file system is ephemeral.

**Comment by gowwe** [comment]
What do I do to bypass this problem?

في الاثنين، ١٣ ديسمبر ٢٠٢١ ٧:٥٨ ص Leonid Pliushch ***@***.***>
كتب:

**Comment by gowwe** [comment]
When I do

rm -rf /etc/apk/cache /etc/motd /media/sda1/*

  setup-disk -m sys /media/sda1/

  extlinux --install /media/sda1/boot

  reboot

في الاثنين، ١٣ ديسمبر ٢٠٢١ ٤:٤٥ ص marcusz ***@***.***> كتب:

**Comment by xeffyr** [comment]
Install it to disk. If have troubles following the instructions in MOTD, follow standard instructions at https://wiki.alpinelinux.org/wiki/Installation. You may need to erase HDD first with `blkdiscard`.
