### ISSUE TITLE
vShell exits with out of memory error

### ISSUE THREAD

**Issue by thunder-coding** [xeffyr/android-vshell#3]
## Problem description
vShell currently exists with out of memory error quickly without providing any other information. The application closes too quick giving very less time for user to find out what's wrong.

## Device information
Moto G4 (Android 7.0)
`Linux localhost 3.10.84-ge03508d-00131-g442576f #1 SMP PREEMPT Wed Mar 28 06:58:16 CDT 2018 armv7l Android`
### Device Memory
Found using `grep MemTotal /proc/meminfo` in Termux
MemTotal:        2951824 kB

## Screen recording of same

[Screen recording](https://user-images.githubusercontent.com/68849076/127264564-0697773e-6697-44f7-9ab8-3775146f2389.mp4)

**Comment by xeffyr** [comment]
How you were able to determine that issue is "out of memory" error? It will do same for any issue since QEMU (which is merged with terminal core) fails to start for some reason.

Which APK file you are using of 5 available?

**Comment by xeffyr** [comment]
There are debug apks which won't exit on QEMU shutdown:
* https://github.com/xeffyr/android-vshell/suites/3331263124/artifacts/78103400
* https://transfer.sh/1L4tFvb/vshell-v1.10-universal-debug.apk

**Comment by xeffyr** [comment]
Now see the error:
![Снимок экрана от 2021-07-28 10-44-13](https://user-images.githubusercontent.com/25881154/127284128-699508df-1428-4421-b3b1-bc7013b3e78c.png)

What could be done here is limiting ram usage to 30% (going with less value will make application useless). However I'm not sure whether this will help. If `ActivityManager.MemoryInfo` returns abnormal values, the RAM used by QEMU could be set to wrong value causing the mentioned out-of-memory condition.

**Comment by thunder-coding** [comment]
I was using universal APK build

**Comment by xeffyr** [comment]
Here are some debug apks to try. Both will show a toast message with current ram allocations.
* Normal: https://transfer.sh/1mqp4J6/vshell-debug-normalmemory.apk
* Reduced RAM: https://transfer.sh/V1/vshell-debug-reducedmemory.apk

**Comment by thunder-coding** [comment]
Here's the screen shot from first APK: 
![Screenshot_20210728-142658](https://user-images.githubusercontent.com/68849076/127298543-5a4019b0-8125-47a3-8973-4fc67d49cf90.png)



And the second APK works fine.

**Comment by xeffyr** [comment]
Ok, I will try to figure something to resolve this issue properly. It is possible that real amount of RAM is lower as significant part could be consumed by zRAM swap.

Could you provide the output of command `free` executed in Termux?

**Comment by xeffyr** [comment]
Try new release: https://github.com/xeffyr/android-vshell/releases/tag/v1.11

**Comment by thunder-coding** [comment]
v1.11 seems to work great

**Comment by jfitie** [comment]
@xeffyr Works fine, but limiting RAM to 2GB on my 16GB RAM S21 Ultra feels unnecessary and too low.

**Comment by xeffyr** [comment]
This application doesn't manage memory like other Android apps. Upper allocation limit is required.

vShell (more specifically: QEMU) will eventually consume all RAM allowed for allocation. If limit is too high, you will end with poor multitasking capabilities or trigger OOM killer terminating either vShell or other currently running application.
