### ISSUE TITLE
My device is 3 ram, can I use it?

### ISSUE THREAD

**Issue by gowwe** [xeffyr/android-vshell#6]
My device is 3 ram, can I use it?

**Comment by xeffyr** [comment]
It works even on devices with 1 GB. The question is only how usable it will be for you, since vShell can use only a fraction of *currently free* device RAM.

**Comment by xeffyr** [comment]
You may need to perform on-hdd system reinstallation by instructions shown after login as by default everything except home directories is stored in tmpfs.
