### ISSUE TITLE
1.13 does not boot

### ISSUE THREAD

**Issue by jfitie** [xeffyr/android-vshell#8]
Just a black screen, had to revert to 1.11. Samsung S21 Ultra on Android 11.
Force stop and clear data did not help.

**Comment by xeffyr** [comment]
How much you waited?

**Comment by jfitie** [comment]
@xeffyr Installing 1.11, running it, then updating to 1.13, works fine
Uninstalling and reinstalling 1.13 OR clearing data on updated 1.13 and it stops working with just a black screen.
In this case, no Storage permission is requested, which might be a hint.
Uninstalling and reinstalling 1.11 works perfectly.

**Comment by xeffyr** [comment]
> In this case, no Storage permission is requested, which might be a hint.

It now works without storage permission. It is not necessary. Also on Android 11 it uses different storage permission which is not disabled when clearing data.

I can't reproduce the issue including the device with stock Android 11 (AArch64).

**Comment by xeffyr** [comment]
On which point exactly it stucks? Does it flashes BIOS info on startup at all?

**Comment by jfitie** [comment]
No, no BIOS info, just a black screen without a cursor.
Same issue with v1.13.1 unfortunately

**Comment by jfitie** [comment]
Also, there is no request for storage access permissions and no toasts are shown.

**Comment by jfitie** [comment]
No ongoing notification as well

**Comment by xeffyr** [comment]
Have you tried v1.12? It doesn't have changes related to storage permission.

**Comment by jfitie** [comment]
Hmmm after a full uninstall, 1.31.1 does request storage permission and works fine.

**Comment by jfitie** [comment]
1.32.2 is fine as well

**Comment by xeffyr** [comment]
So 1.13.2 works after full re-installation?

**Comment by jfitie** [comment]
Yes,  that is correct
