### ISSUE TITLE
Clear command does not work and is kind a slow

### ISSUE THREAD

**Issue by T-Dynamos** [xeffyr/android-vshell#9]
Clear does not work like termux and there are some ui problem the neofetch also stucks and has other many bugs

**Comment by xeffyr** [comment]
Most of "issues" are there because terminal is a serial console actually. You have to use `reset` instead of `clear` and `resize` command after each screen size change.

https://github.com/xeffyr/android-vshell/blob/master/user-guide/guide.md.in#L61-L74

**Comment by T-Dynamos** [comment]
> Most of "issues" are there because terminal is a serial console actually. You have to use `reset` instead of `clear` and `resize` command after each screen size change (especially if you managed to disable default shell settings somehow).
> 
> https://github.com/xeffyr/android-vshell/blob/master/user-guide/guide.md.in#L61-L74

Ohk
